[project]
name = "data-market1-manel"
version = "0.1.0"
description = "E1 E2 E3 E4 E5"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
]
